# Generated by Django 5.1.4 on 2024-12-29 07:45

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='purchase_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.ImageField(upload_to=books.models.book_image_upload_to),
        ),
    ]
