# Generated by Django 5.1.4 on 2025-01-09 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
